### ISSUE TITLE
ประชุมครั้ง1 คิดหัวข้อโครงงาน แบ่งหน้าที่รับผิดชอบ

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#1]
วันที่ 3 กันยายน 13.00

**Comment by KP2301** [comment]
ให้คิด concept game ของเเต่ละคนมาเสนอในวันที่ 3 กย แล้วเลือกกันนะครับ

**Comment by aeiout** [comment]
หน้าที่คร่าวๆนะครับทุกคน
วิน-manager,programmer
เอื้อ-programmer,tester
ฟิล์ม-assistant promgrammer,designer
พีพี-designer,tester
ถ้ามีความคิดเห็นอย่างไรกับหน้าที่ให้comment มานะครับว่าอยากทำหน้าที่อะไร เเล้ววันที่ 3 มาสรุปลงไสลกันครับ

**Comment by PP2546** [comment]
เราอยากให้ @KP2301 สรุปที่เราคุยกันคร่าวๆตอนนั้นได้มั้ยเพื่อที่จะให้ @penpizza ได้รู้ด้วย อย่างน้อยเราก็จะได้มี concept ไว้เผื่อกรณีคิดไม่ออกว่าจะทำอะไรต่อ

**Comment by KP2301** [comment]
> เราอยากให้ @KP2301 สรุปที่เราคุยกันคร่าวๆตอนนั้นได้มั้ยเพื่อที่จะให้ @penpizza ได้รู้ด้วย อย่างน้อยเราก็จะได้มี concept ไว้เผื่อกรณีคิดไม่ออกว่าจะทำอะไรต่อ

OK

**Comment by KP2301** [comment]
![Screenshot_20220817-165722_Samsung Notes.jpg](https://user-images.githubusercontent.com/110970175/185091526-c1b67983-5189-4c4a-b674-a803370ba547.jpg)

**Comment by KP2301** [comment]
> ![Screenshot_20220817-165722_Samsung Notes.jpg](https://user-images.githubusercontent.com/110970175/185091526-c1b67983-5189-4c4a-b674-a803370ba547.jpg)

ถ้าโดนน้ำท่วมเเล้วพวกเค้าคุยไว้ว่าน่าจะมี Jump Scare ตอนที่Gameover

**Comment by PP2546** [comment]
![1458614D-203D-445A-BFB4-E1D144A23A0F](https://user-images.githubusercontent.com/110951565/185093032-85a134ab-dbb5-4e1a-9e0a-e3abdb5e9553.jpeg)
อันนี้ที่ลองทำพาวเวอร์พ้อยดู

**Comment by KP2301** [comment]
พรุ้งนี้ประชุมตอน13.00นะครับ น่าจะทางzoomครับ

**Comment by penpizza** [comment]
![ร่างเกม2](https://user-images.githubusercontent.com/110964198/188258071-cefc9965-2ee5-4960-bb46-dbb01ac22492.jpg)
![ร่างเกม](https://user-images.githubusercontent.com/110964198/188258073-31760e84-0606-456a-94b3-3e0b489954e0.jpg)

**Comment by penpizza** [comment]
![2CBE4754-89B3-4BD5-93C6-C5CDA5B7130F](https://user-images.githubusercontent.com/110964198/188325456-2f5a48ea-209f-4193-a1c7-b873ef9813c1.jpeg)
![BC644053-2F9D-4883-A9C0-63305BB2D373](https://user-images.githubusercontent.com/110964198/188325451-89811ce8-0e82-4154-9ca9-bc0af6b80f71.jpeg)
![E20D0490-7064-4293-9704-486DBBE2B8ED](https://user-images.githubusercontent.com/110964198/188325459-3de52ceb-b8c8-49db-a71c-f269f36d3fc8.jpeg)

**Comment by PP2546** [comment]
![DFCD6148-882D-4078-8101-B3DD4D26B59C](https://user-images.githubusercontent.com/110951565/188524567-9cfc9a56-a469-4241-a091-51c1bbe12119.png)

**Comment by penpizza** [comment]
https://www.canva.com/design/DAFLbLpyRfQ/vtDP4ex-IyXr6qAF8bA6pw/view?utm_content=DAFLbLpyRfQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
