### ISSUE TITLE
ประชุมครั้งที่2 เตรียมนำเสนอความคืบหน้าโครงงาน

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#2]

**Comment by KP2301** [comment]
นัดประชุมวันเสาร์10 หรือ วันอาทิตย์ที่11 นะครับ เวลาจะเเจ้งให้ทราบอีกทีครับ

**Comment by KP2301** [comment]
วันอาทิต 2 ทุ่ม

**Comment by PP2546** [comment]
![5ABA99E6-3E49-4C41-A6F2-F7F6BF749D48](https://user-images.githubusercontent.com/110951565/189800944-7b5ad93b-5676-4a79-8cf6-8529f750bf73.jpeg)
![058C49A5-7A5D-4193-A3B0-54962639B9DE](https://user-images.githubusercontent.com/110951565/189800947-633025da-0c6a-413b-a6c4-dc24dce5a487.jpeg)
![08F9D15C-25F0-4D46-AB4F-0CF5AD2DAFD9](https://user-images.githubusercontent.com/110951565/189800951-4e1846dd-3c22-443a-8aba-21475cc17f0f.jpeg)
![1BC332F6-79BD-42D5-8FB8-7E7FE6319C65](https://user-images.githubusercontent.com/110951565/189800953-1a95ab0c-7201-48da-8c15-2f91090f6677.jpeg)
อันนี้เราลองให้วินใส่ละโอเคพอได้เดี๋ยวอาจจะปรับนิดหน่อย

**Comment by PP2546** [comment]
![E2482BD1-6E45-40D5-93A4-8952847EF338](https://user-images.githubusercontent.com/110951565/189801055-a50d7a6c-f34f-406f-b2e6-d4ccc92bf087.png)
ส่วนอันนี้ยังคิดไม่ออกว่าจะยังไงต่อ

**Comment by penpizza** [comment]
Game Asset
https://drive.google.com/drive/folders/1j-VU7M3IDWSJ92spJINtxYfyTtwAdKx1?usp=sharing

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/731337823

**Comment by KP2301** [comment]
หน้าที่โดยละเอียดของ Programer 
วิน รับผิดชอบด่าน 1 4
เอี้อ รับผิดชอบด่าน 2 3
