### ISSUE TITLE
ฉาก คืบหน้า #1

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#4]
ให้ทีม design ส่งความคืบหน้าฉากมาในนี้ได้เลยครับ

**Comment by penpizza** [comment]
ฉาก level 1
![ฉาก 1](https://user-images.githubusercontent.com/110964198/190056667-25838961-1eae-41bb-b14a-21baeee7ef98.jpg)
ฉาก level 2
![ฉาก 2](https://user-images.githubusercontent.com/110964198/190056721-3a1f41a1-22a7-4f48-b8f8-a3a81dff6f86.jpg)
ฉาก level 3
![ฉาก 3](https://user-images.githubusercontent.com/110964198/190056750-80619698-95c6-4a06-89fb-e3d9fb9f2b02.jpg)
ฉาก level 4
![ฉาก 4](https://user-images.githubusercontent.com/110964198/190056786-fd08f96f-0fd5-4cd9-aaa4-03e8a65bea48.jpg)

**Comment by penpizza** [comment]
Game asset level 1
![ที่กันประตูด้านบน](https://user-images.githubusercontent.com/110964198/190056954-2a484ed6-d016-4cab-888b-e98200cb1a60.png)
![ประตู](https://user-images.githubusercontent.com/110964198/190056962-ebd7c092-ec81-4844-94a2-68d50e3f9eda.png)
![block พื้น](https://user-images.githubusercontent.com/110964198/190056967-e598b51e-70e3-430c-8800-c92062a8946a.png)
![block ลอยยาว](https://user-images.githubusercontent.com/110964198/190056968-37b3b7c5-6587-481d-9c5a-34fd543ba83f.png)
![คันโยกเปิด](https://user-images.githubusercontent.com/110964198/190056972-120957aa-d41e-4eb1-9861-f61bf898723c.png)
![ฐานประตู](https://user-images.githubusercontent.com/110964198/190056975-1f955beb-64e1-4e38-ad04-5faaf1b34c3d.png)
![กล่องเก็บ item](https://user-images.githubusercontent.com/110964198/190057048-f9d89d3e-3e1b-40f1-80d7-41ea0d541b40.png)
Game asset level 2
![ลูกแก้ว](https://user-images.githubusercontent.com/110964198/190057003-0d07a329-f25f-4e54-9114-2edc16270a6b.png)
![บล็อกพื้น](https://user-images.githubusercontent.com/110964198/190057006-1b3f6d96-c7fd-421b-b541-0c30d1267f1b.png)
Game asset level 3
![พื้นกระจก](https://user-images.githubusercontent.com/110964198/190057091-df88d523-8ae0-424c-92e3-c7ee1d2fc83f.png)
![block 1](https://user-images.githubusercontent.com/110964198/190057089-127679dd-2e4d-491e-a85a-5166ad09a725.png)
Game asset level 4
![กระสุน](https://user-images.githubusercontent.com/110964198/190057135-918e21f1-67f6-4b48-809a-0175d6450950.png)
![block พื้น](https://user-images.githubusercontent.com/110964198/190057574-d978f6e8-ff4b-4ac9-a00f-c5128cddaee0.png)

**Comment by PP2546** [comment]
![5F0F485F-9CA9-454C-8A09-03F1EFD523CC](https://user-images.githubusercontent.com/110951565/190057567-f03db82d-fb51-4c27-9c1f-7df4aaa4adf6.png)
![26418886-D6C8-4F59-8CF4-6DB36C4684E1](https://user-images.githubusercontent.com/110951565/190057584-f43d7a45-d854-46f5-a2d3-bec2bfbaa0ff.png)
![5620CE4A-DF62-4695-BACE-D2EF0CA912A0](https://user-images.githubusercontent.com/110951565/190057587-a7b66aa5-e81b-451d-a2f7-e1147a76d18f.png)
![F3C6D5FB-8F5B-4176-921A-386E045BC536](https://user-images.githubusercontent.com/110951565/190057591-b2decb3f-3396-499d-b9f5-3daaa883c7ae.png)
![30B95EEB-FE40-4488-A125-9BD5B50AF8F0](https://user-images.githubusercontent.com/110951565/190057592-4956a4dd-9378-4bb5-903f-d5f7173c6f91.png)
![945CD6A9-54DA-4681-8596-EA71EFD249F0](https://user-images.githubusercontent.com/110951565/190057595-b059bf72-33c8-45ce-80f3-30f47efd7bf0.png)
If u win

**Comment by PP2546** [comment]
![35E84E09-FFF5-4AA6-8D74-94E5EB207CBD](https://user-images.githubusercontent.com/110951565/190057699-c2417ea3-91af-4217-8d46-1e4e3ed5acd7.jpeg)
![8FC540C4-CC15-4ACF-9B82-447A81B0E297](https://user-images.githubusercontent.com/110951565/190057704-216f82dc-8e58-4896-ae64-b35119e76305.jpeg)
![56AED31A-BA48-439C-9AE4-0DF0D07B9F7C](https://user-images.githubusercontent.com/110951565/190057709-a5ff61e3-7c66-4a15-b35e-d73ca4f37ea4.jpeg)
![C524338A-6DC2-46E6-A23B-54C488303806](https://user-images.githubusercontent.com/110951565/190057711-d032689e-5124-4e45-909f-b5fb71db96a4.jpeg)
Bad end but I will repaint

**Comment by penpizza** [comment]
player  level 1-3
![player2](https://user-images.githubusercontent.com/110964198/190057724-24d0fe71-74f4-4fef-8332-9428aa7ba0fd.png)
![player3](https://user-images.githubusercontent.com/110964198/190057725-fa5430e5-d749-4b7b-8466-2315f155ce74.png)
![player1](https://user-images.githubusercontent.com/110964198/190057728-3fae900c-13ac-45df-863e-03a0116853c0.png)
player  level 4
![playerถือปืน1](https://user-images.githubusercontent.com/110964198/190057764-cc954856-b1d6-4467-b4e7-bc9c85106bf5.png)
![playerถือปืน2](https://user-images.githubusercontent.com/110964198/190057768-7bf1e3ce-2ca8-47ee-9843-48b19c8174d4.png)
![playerถือปืน3](https://user-images.githubusercontent.com/110964198/190057772-1ce02e55-ce60-47c6-b7b1-9f6af49c4c21.png)
ผู้คุม
![ผู้คุม2](https://user-images.githubusercontent.com/110964198/190057813-4b96a414-eab3-4815-94cc-f7220e0a96a7.png)
![ผู้คุม3](https://user-images.githubusercontent.com/110964198/190057814-cf9ed20a-ac95-40f6-ad80-c66651e1f792.png)
![ผู้คุม1](https://user-images.githubusercontent.com/110964198/190057809-88319b94-bf63-460a-a3d4-d6691cd95958.png)
ตุ๊กตายองฮี
![ตุ๊กตาโกโกวา](https://user-images.githubusercontent.com/110964198/190057990-c43d8b37-d9c3-4110-b420-7d46e941303e.png)
