### ISSUE TITLE
ความคืบหน้า coding

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#6]
Program

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/731713204

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/731433487

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/729030452

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/729577023

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/729577023

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/731337823

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/731433487

**Comment by KP2301** [comment]
งานcode ส่วนที่เหลือ มี ด่าน4 3 เดี๋ยวเค้าทำเอง
ส่วนฉากเริ่ม จบ เกมชนะ เอื้อทำนะ

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/731713204

**Comment by KP2301** [comment]
อันนี้เป็นcode ล่าสุดที่เขียนไปคือมีเสียงโกโกวาเเล้ว ปรับชนาดตัวละครด่านสาม สี่เเล้ว

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/731713204
น่าจะสมบูรณ์แล้วนะ

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/733278137
ยังเหลือพวกbugที่เป็นการหายไปของกำแพงเมื่อกดretry

**Comment by aeiout** [comment]
https://scratch.mit.edu/projects/733278137
น่าจะสมบูรณ์ละ

**Comment by KP2301** [comment]
https://scratch.mit.edu/projects/734351717 
เพิ่มเสียง
