### ISSUE TITLE
ฉากคืบหน้า#2

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#7]
เมื่อกี้จะทำ Happy Ending ใช่มะ @PP2546

**Comment by PP2546** [comment]
เดี๋ยวเราคิดว่าเราน่าจะทำใหม่อยู่คือมันยังไม่ค่อยsmooth เดี่ยวถ้ายังไงเดี่ยวส่งมาอีกที เพราะว่าฉากทั้งสองที่จบอ่ะมันใปล้เคียงกันเกินไป

**Comment by PP2546** [comment]
![B3227AAC-2B2C-493B-99AF-2B5AE81D7DB3](https://user-images.githubusercontent.com/110951565/190327349-c6663a80-32af-4a03-848b-9771120542af.png)
![50FD9240-A739-4DD5-B815-2798C357BA3D](https://user-images.githubusercontent.com/110951565/190327378-48a9e427-4358-4848-9913-421a979ccce0.png)
![7388C8C9-A321-4085-BB43-76D0320F31BC](https://user-images.githubusercontent.com/110951565/190327390-644b734a-95f3-456d-8d27-efdbc0bf8e09.png)
![A3895BD0-999A-4F23-9CCE-79126BBE10D0](https://user-images.githubusercontent.com/110951565/190327396-02341001-9faf-44a5-b4f2-9e8c7693275b.png)
![CCB6C138-846B-4840-8961-205C23D628BD](https://user-images.githubusercontent.com/110951565/190327401-dc391122-49c9-4413-af5f-41877c30b66e.png)
![EBCB0931-B750-44C8-AF56-BFAF31C6C5E7](https://user-images.githubusercontent.com/110951565/190327409-b9310150-f91b-44f8-860c-f6828cc18ac8.png)
![796FA9A5-1299-4103-A557-1740B3DB08D1](https://user-images.githubusercontent.com/110951565/190327415-e90093c6-b74b-4453-bf37-f8768e3824ca.png)
![CC15997A-F22E-49F1-8906-EA4693AC9CA0](https://user-images.githubusercontent.com/110951565/190327420-f66e4e80-ee8d-49c8-af5a-e4ef972f7c5b.png)
![33308663-632D-445D-A89B-E7CF4BBE55E4](https://user-images.githubusercontent.com/110951565/190327425-aede718b-9926-444e-a69e-89d5233a56c8.png)
![2BFE0BD3-9089-45A1-9180-5DDD54607D03](https://user-images.githubusercontent.com/110951565/190327431-478ab6ca-fe68-4f12-92a9-ba043ce05856.png)
![E41759BB-8F4C-401B-B9C4-DF3BBB3F8318](https://user-images.githubusercontent.com/110951565/190327435-5e674e09-6c0e-41b7-ac20-6a0be46dcccf.png)
![1245C2C0-7065-4ADA-B6C1-9CB162C2801E](https://user-images.githubusercontent.com/110951565/190327439-aba1b468-fd52-4047-bff4-1c4a90b05150.png)
![F99098F9-B67F-4BE9-9E4B-0B77605F00D9](https://user-images.githubusercontent.com/110951565/190327443-4856a067-23b5-40b0-97dc-c11910a7fa36.png)
![5360FC25-CDF7-47F6-A913-CFC4FF628DA5](https://user-images.githubusercontent.com/110951565/190327448-ab636d39-f8cd-448c-868e-04c3436e8713.png)
![467CE213-1384-4D77-99FE-451D4534F67D](https://user-images.githubusercontent.com/110951565/190327454-4e8c3ba8-2100-4bce-8b58-1df193168acf.png)
![96FF770D-4381-4922-9594-5BC3A8D9C7CA](https://user-images.githubusercontent.com/110951565/190327459-140c0470-be0f-4e2f-8e20-a2ad5ce8abe1.png)
![77D728B9-4220-4EE1-9E36-0BF9081463C8](https://user-images.githubusercontent.com/110951565/190327464-5c70c7bb-f118-4885-abe5-f49f92c2014c.png)
![BAF55638-DCA5-4E7C-8303-CF160BD24576](https://user-images.githubusercontent.com/110951565/190327470-36f9db9c-1b12-46de-9abe-561ebff14979.png)
![49B30C2C-180B-42ED-B00E-924472E57BA2](https://user-images.githubusercontent.com/110951565/190327474-d56f6a27-2b77-4e70-bdf5-38a88e63c9be.png)
![6EEEBBE4-2407-473F-BC8D-64EB2F48E8A0](https://user-images.githubusercontent.com/110951565/190327478-620882b8-e29e-4075-a8d6-5fcdd19fbba8.png)
![2E52688E-E0D8-4778-840B-39BBC0C3A2D4](https://user-images.githubusercontent.com/110951565/190327483-08a3944d-f5b7-45f2-b995-835dc6805290.png)
![6E752D85-2263-4CE4-8011-DAFE4C4C353D](https://user-images.githubusercontent.com/110951565/190327487-3517f960-4566-4450-945f-d32ef1490482.png)
![C05D092B-542A-4897-83F5-3FF98ECCED0F](https://user-images.githubusercontent.com/110951565/190327500-cbf128a2-17be-443c-bd17-a32217c11c44.png)
![7F16D3E7-7140-45DD-ADDD-64A65E5E5F66](https://user-images.githubusercontent.com/110951565/190327504-c45ac247-50c5-480f-849e-2600ed47ed59.png)
![4A4D91FB-5D8B-4C0D-8B8F-95A81A80272C](https://user-images.githubusercontent.com/110951565/190327509-0b0b6583-75b5-4c52-8399-354f9c9025cf.png)
![00DEE1ED-E0A8-4BAA-BC2F-36DA1890B347](https://user-images.githubusercontent.com/110951565/190327514-bab146a5-09ca-4c72-bcd7-22c5fd531781.png)
![57F5B37E-4450-4156-B0A8-AC5DF085371A](https://user-images.githubusercontent.com/110951565/190327522-89f1f932-af7c-44e1-b128-d0b9f42f350a.png)
 ฉากจบดีๆทั้งหมดเรียงจากบนลงมาล่าง

**Comment by PP2546** [comment]
**สลับฉากที่มืดหมดกับคำว่าvictory
****สลับฉากที่อยู่ล่างสุดขึ้นไปประมาณ9

**Comment by PP2546** [comment]
ส่วนอันนี้เป็นฉากร้ายแก้ไขตัวที่เป็นหนังสือจบ

**Comment by PP2546** [comment]
![12355145-7575-464E-BA21-74FB12DD73A7](https://user-images.githubusercontent.com/110951565/190327907-a66ac46e-77da-467b-9428-0397b667b46b.jpeg)
![97262566-4622-4968-AF5F-A516817CA64B](https://user-images.githubusercontent.com/110951565/190327925-ccefac12-694f-4483-963d-45edeebd297a.jpeg)
![2402ECFF-A379-492B-8FCA-D2CCFEFE466F](https://user-images.githubusercontent.com/110951565/190327935-2cde4d25-a7b2-48e0-9fd3-6787a8b45471.jpeg)
![3DBDB6D0-D50F-486C-B41A-1BC873B8DD30](https://user-images.githubusercontent.com/110951565/190327943-3cc0e71a-9d7a-4e15-aa84-b7fd049ae259.jpeg)
![21873710-33DB-42C7-A005-92859F72E0C7](https://user-images.githubusercontent.com/110951565/190327949-a8a0ddeb-6e2d-4ec0-80c2-aa12f14e0dc4.jpeg)
![37ED2864-06F7-4952-A887-E99D8BB6CCA6](https://user-images.githubusercontent.com/110951565/190327953-147786cc-4115-4b7a-9edf-3ccc3505567b.png)
