### ISSUE TITLE
ฉากเริ่มเกมส์ 

### ISSUE THREAD

**Issue by KP2301** [KP2301/cpe103-test-group-17#8]
ฟิลม์ จะทำฉากเริ่มเกมส์ชะมะ ถ้ามีแบบส่งมาได้เลยนะ จะได้คุยกัน

**Comment by PP2546** [comment]
อันนี้ฟิล์มจะเป็นคนทำนะ เห็นฟิล์มบอกเราว่าจะทำแนวอะไรสักอย่าง เดี๋ยวให้ฟิล์มเอาแบบมาให้ดู

**Comment by PP2546** [comment]
@penpizza

**Comment by penpizza** [comment]
ประมาณนี้ๆ
![image](https://user-images.githubusercontent.com/110964198/190092415-75bd9f6c-bae7-43fe-8e84-4011978d0555.png)
![image](https://user-images.githubusercontent.com/110964198/190092453-4dbd7b87-ce6b-4163-9d58-321daf1ae014.png)

**Comment by PP2546** [comment]
ฟิล์มมันจะยากไปป่าว แต่จะทำเป็นพิกเซลใช่ป่ะ @penpizza

**Comment by penpizza** [comment]
พอได้ๆ ยังมีเวลาอยู่ ทำเป็น pixel มันแปปเดียว

**Comment by penpizza** [comment]
![image](https://user-images.githubusercontent.com/110964198/190666292-90731cd5-cf56-40c6-82af-6e35c159a5ea.jpeg)
